#!/bin/bash

read_configs(){
	cfg_file=$1.config
	cfg_key=$2
	[ ! -f "./${cfg_file}" ] && return
	[ -z "${cfg_key}" ] && return
	awk -F"=" "/${cfg_key}/ { print \$2 }" ${cfg_file}


}
read_configs $1 $2
